version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - carrental-net

  user-service:
    build: ./user-service
    ports:
      - "50051:50051"
      - "2112:2112"   # 🔥 важный порт для метрик Prometheus
    env_file:
      - ./user-service/.env
    depends_on:
      - mongo
      - nats
    networks:
      - carrental-net

  car-service:
    build: ./car-service
    ports:
      - "50052:50052"
      - "2113:2113"
    depends_on:
      - mongo
    networks:
      - carrental-net

  rental-service:
    build: ./rental-service
    ports:
      - "50053:50053"
    depends_on:
      - mongo
    networks:
      - carrental-net

  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - car-service
      - rental-service
    networks:
      - carrental-net

  nats:
    image: nats
    ports:
      - "4222:4222"
    networks:
      - carrental-net

  consumer-service:
    build: ./consumer-service
    depends_on:
      - nats
    networks:
      - carrental-net

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - carrental-net

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - carrental-net

volumes:
  mongo-data:
  grafana-storage:

networks:
  carrental-net:
