// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.30.2
// source: proto/rental.proto

package rental

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RentalService_CreateRental_FullMethodName     = "/rental.RentalService/CreateRental"
	RentalService_EndRental_FullMethodName        = "/rental.RentalService/EndRental"
	RentalService_GetRental_FullMethodName        = "/rental.RentalService/GetRental"
	RentalService_ListRentals_FullMethodName      = "/rental.RentalService/ListRentals"
	RentalService_ListByUser_FullMethodName       = "/rental.RentalService/ListByUser"
	RentalService_ListByCar_FullMethodName        = "/rental.RentalService/ListByCar"
	RentalService_GetActiveRentals_FullMethodName = "/rental.RentalService/GetActiveRentals"
	RentalService_DeleteRental_FullMethodName     = "/rental.RentalService/DeleteRental"
	RentalService_UpdateType_FullMethodName       = "/rental.RentalService/UpdateType"
)

// RentalServiceClient is the client API for RentalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RentalServiceClient interface {
	CreateRental(ctx context.Context, in *CreateRentalRequest, opts ...grpc.CallOption) (*Rental, error)
	EndRental(ctx context.Context, in *EndRentalRequest, opts ...grpc.CallOption) (*Rental, error)
	GetRental(ctx context.Context, in *GetRentalRequest, opts ...grpc.CallOption) (*Rental, error)
	ListRentals(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RentalList, error)
	ListByUser(ctx context.Context, in *UserIdRequest, opts ...grpc.CallOption) (*RentalList, error)
	ListByCar(ctx context.Context, in *CarIdRequest, opts ...grpc.CallOption) (*RentalList, error)
	GetActiveRentals(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RentalList, error)
	DeleteRental(ctx context.Context, in *RentalIdRequest, opts ...grpc.CallOption) (*Empty, error)
	UpdateType(ctx context.Context, in *UpdateTypeRequest, opts ...grpc.CallOption) (*Rental, error)
}

type rentalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRentalServiceClient(cc grpc.ClientConnInterface) RentalServiceClient {
	return &rentalServiceClient{cc}
}

func (c *rentalServiceClient) CreateRental(ctx context.Context, in *CreateRentalRequest, opts ...grpc.CallOption) (*Rental, error) {
	out := new(Rental)
	err := c.cc.Invoke(ctx, RentalService_CreateRental_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rentalServiceClient) EndRental(ctx context.Context, in *EndRentalRequest, opts ...grpc.CallOption) (*Rental, error) {
	out := new(Rental)
	err := c.cc.Invoke(ctx, RentalService_EndRental_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rentalServiceClient) GetRental(ctx context.Context, in *GetRentalRequest, opts ...grpc.CallOption) (*Rental, error) {
	out := new(Rental)
	err := c.cc.Invoke(ctx, RentalService_GetRental_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rentalServiceClient) ListRentals(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RentalList, error) {
	out := new(RentalList)
	err := c.cc.Invoke(ctx, RentalService_ListRentals_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rentalServiceClient) ListByUser(ctx context.Context, in *UserIdRequest, opts ...grpc.CallOption) (*RentalList, error) {
	out := new(RentalList)
	err := c.cc.Invoke(ctx, RentalService_ListByUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rentalServiceClient) ListByCar(ctx context.Context, in *CarIdRequest, opts ...grpc.CallOption) (*RentalList, error) {
	out := new(RentalList)
	err := c.cc.Invoke(ctx, RentalService_ListByCar_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rentalServiceClient) GetActiveRentals(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RentalList, error) {
	out := new(RentalList)
	err := c.cc.Invoke(ctx, RentalService_GetActiveRentals_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rentalServiceClient) DeleteRental(ctx context.Context, in *RentalIdRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, RentalService_DeleteRental_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rentalServiceClient) UpdateType(ctx context.Context, in *UpdateTypeRequest, opts ...grpc.CallOption) (*Rental, error) {
	out := new(Rental)
	err := c.cc.Invoke(ctx, RentalService_UpdateType_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RentalServiceServer is the server API for RentalService service.
// All implementations must embed UnimplementedRentalServiceServer
// for forward compatibility
type RentalServiceServer interface {
	CreateRental(context.Context, *CreateRentalRequest) (*Rental, error)
	EndRental(context.Context, *EndRentalRequest) (*Rental, error)
	GetRental(context.Context, *GetRentalRequest) (*Rental, error)
	ListRentals(context.Context, *Empty) (*RentalList, error)
	ListByUser(context.Context, *UserIdRequest) (*RentalList, error)
	ListByCar(context.Context, *CarIdRequest) (*RentalList, error)
	GetActiveRentals(context.Context, *Empty) (*RentalList, error)
	DeleteRental(context.Context, *RentalIdRequest) (*Empty, error)
	UpdateType(context.Context, *UpdateTypeRequest) (*Rental, error)
	mustEmbedUnimplementedRentalServiceServer()
}

// UnimplementedRentalServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRentalServiceServer struct {
}

func (UnimplementedRentalServiceServer) CreateRental(context.Context, *CreateRentalRequest) (*Rental, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRental not implemented")
}
func (UnimplementedRentalServiceServer) EndRental(context.Context, *EndRentalRequest) (*Rental, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndRental not implemented")
}
func (UnimplementedRentalServiceServer) GetRental(context.Context, *GetRentalRequest) (*Rental, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRental not implemented")
}
func (UnimplementedRentalServiceServer) ListRentals(context.Context, *Empty) (*RentalList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRentals not implemented")
}
func (UnimplementedRentalServiceServer) ListByUser(context.Context, *UserIdRequest) (*RentalList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListByUser not implemented")
}
func (UnimplementedRentalServiceServer) ListByCar(context.Context, *CarIdRequest) (*RentalList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListByCar not implemented")
}
func (UnimplementedRentalServiceServer) GetActiveRentals(context.Context, *Empty) (*RentalList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActiveRentals not implemented")
}
func (UnimplementedRentalServiceServer) DeleteRental(context.Context, *RentalIdRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRental not implemented")
}
func (UnimplementedRentalServiceServer) UpdateType(context.Context, *UpdateTypeRequest) (*Rental, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateType not implemented")
}
func (UnimplementedRentalServiceServer) mustEmbedUnimplementedRentalServiceServer() {}

// UnsafeRentalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RentalServiceServer will
// result in compilation errors.
type UnsafeRentalServiceServer interface {
	mustEmbedUnimplementedRentalServiceServer()
}

func RegisterRentalServiceServer(s grpc.ServiceRegistrar, srv RentalServiceServer) {
	s.RegisterService(&RentalService_ServiceDesc, srv)
}

func _RentalService_CreateRental_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRentalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RentalServiceServer).CreateRental(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RentalService_CreateRental_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RentalServiceServer).CreateRental(ctx, req.(*CreateRentalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RentalService_EndRental_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndRentalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RentalServiceServer).EndRental(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RentalService_EndRental_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RentalServiceServer).EndRental(ctx, req.(*EndRentalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RentalService_GetRental_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRentalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RentalServiceServer).GetRental(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RentalService_GetRental_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RentalServiceServer).GetRental(ctx, req.(*GetRentalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RentalService_ListRentals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RentalServiceServer).ListRentals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RentalService_ListRentals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RentalServiceServer).ListRentals(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RentalService_ListByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RentalServiceServer).ListByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RentalService_ListByUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RentalServiceServer).ListByUser(ctx, req.(*UserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RentalService_ListByCar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CarIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RentalServiceServer).ListByCar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RentalService_ListByCar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RentalServiceServer).ListByCar(ctx, req.(*CarIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RentalService_GetActiveRentals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RentalServiceServer).GetActiveRentals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RentalService_GetActiveRentals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RentalServiceServer).GetActiveRentals(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RentalService_DeleteRental_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RentalIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RentalServiceServer).DeleteRental(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RentalService_DeleteRental_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RentalServiceServer).DeleteRental(ctx, req.(*RentalIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RentalService_UpdateType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RentalServiceServer).UpdateType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RentalService_UpdateType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RentalServiceServer).UpdateType(ctx, req.(*UpdateTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RentalService_ServiceDesc is the grpc.ServiceDesc for RentalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RentalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rental.RentalService",
	HandlerType: (*RentalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRental",
			Handler:    _RentalService_CreateRental_Handler,
		},
		{
			MethodName: "EndRental",
			Handler:    _RentalService_EndRental_Handler,
		},
		{
			MethodName: "GetRental",
			Handler:    _RentalService_GetRental_Handler,
		},
		{
			MethodName: "ListRentals",
			Handler:    _RentalService_ListRentals_Handler,
		},
		{
			MethodName: "ListByUser",
			Handler:    _RentalService_ListByUser_Handler,
		},
		{
			MethodName: "ListByCar",
			Handler:    _RentalService_ListByCar_Handler,
		},
		{
			MethodName: "GetActiveRentals",
			Handler:    _RentalService_GetActiveRentals_Handler,
		},
		{
			MethodName: "DeleteRental",
			Handler:    _RentalService_DeleteRental_Handler,
		},
		{
			MethodName: "UpdateType",
			Handler:    _RentalService_UpdateType_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/rental.proto",
}
