// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: proto/rental.proto

package rental

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RentalService_CreateRental_FullMethodName = "/rental.RentalService/CreateRental"
	RentalService_EndRental_FullMethodName    = "/rental.RentalService/EndRental"
	RentalService_GetRental_FullMethodName    = "/rental.RentalService/GetRental"
	RentalService_ListRentals_FullMethodName  = "/rental.RentalService/ListRentals"
)

// RentalServiceClient is the client API for RentalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RentalServiceClient interface {
	CreateRental(ctx context.Context, in *CreateRentalRequest, opts ...grpc.CallOption) (*Rental, error)
	EndRental(ctx context.Context, in *EndRentalRequest, opts ...grpc.CallOption) (*Rental, error)
	GetRental(ctx context.Context, in *GetRentalRequest, opts ...grpc.CallOption) (*Rental, error)
	ListRentals(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RentalList, error)
}

type rentalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRentalServiceClient(cc grpc.ClientConnInterface) RentalServiceClient {
	return &rentalServiceClient{cc}
}

func (c *rentalServiceClient) CreateRental(ctx context.Context, in *CreateRentalRequest, opts ...grpc.CallOption) (*Rental, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Rental)
	err := c.cc.Invoke(ctx, RentalService_CreateRental_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rentalServiceClient) EndRental(ctx context.Context, in *EndRentalRequest, opts ...grpc.CallOption) (*Rental, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Rental)
	err := c.cc.Invoke(ctx, RentalService_EndRental_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rentalServiceClient) GetRental(ctx context.Context, in *GetRentalRequest, opts ...grpc.CallOption) (*Rental, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Rental)
	err := c.cc.Invoke(ctx, RentalService_GetRental_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rentalServiceClient) ListRentals(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RentalList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RentalList)
	err := c.cc.Invoke(ctx, RentalService_ListRentals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RentalServiceServer is the server API for RentalService service.
// All implementations must embed UnimplementedRentalServiceServer
// for forward compatibility.
type RentalServiceServer interface {
	CreateRental(context.Context, *CreateRentalRequest) (*Rental, error)
	EndRental(context.Context, *EndRentalRequest) (*Rental, error)
	GetRental(context.Context, *GetRentalRequest) (*Rental, error)
	ListRentals(context.Context, *Empty) (*RentalList, error)
	mustEmbedUnimplementedRentalServiceServer()
}

// UnimplementedRentalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRentalServiceServer struct{}

func (UnimplementedRentalServiceServer) CreateRental(context.Context, *CreateRentalRequest) (*Rental, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRental not implemented")
}
func (UnimplementedRentalServiceServer) EndRental(context.Context, *EndRentalRequest) (*Rental, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndRental not implemented")
}
func (UnimplementedRentalServiceServer) GetRental(context.Context, *GetRentalRequest) (*Rental, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRental not implemented")
}
func (UnimplementedRentalServiceServer) ListRentals(context.Context, *Empty) (*RentalList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRentals not implemented")
}
func (UnimplementedRentalServiceServer) mustEmbedUnimplementedRentalServiceServer() {}
func (UnimplementedRentalServiceServer) testEmbeddedByValue()                       {}

// UnsafeRentalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RentalServiceServer will
// result in compilation errors.
type UnsafeRentalServiceServer interface {
	mustEmbedUnimplementedRentalServiceServer()
}

func RegisterRentalServiceServer(s grpc.ServiceRegistrar, srv RentalServiceServer) {
	// If the following call pancis, it indicates UnimplementedRentalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RentalService_ServiceDesc, srv)
}

func _RentalService_CreateRental_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRentalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RentalServiceServer).CreateRental(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RentalService_CreateRental_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RentalServiceServer).CreateRental(ctx, req.(*CreateRentalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RentalService_EndRental_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndRentalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RentalServiceServer).EndRental(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RentalService_EndRental_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RentalServiceServer).EndRental(ctx, req.(*EndRentalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RentalService_GetRental_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRentalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RentalServiceServer).GetRental(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RentalService_GetRental_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RentalServiceServer).GetRental(ctx, req.(*GetRentalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RentalService_ListRentals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RentalServiceServer).ListRentals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RentalService_ListRentals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RentalServiceServer).ListRentals(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// RentalService_ServiceDesc is the grpc.ServiceDesc for RentalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RentalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rental.RentalService",
	HandlerType: (*RentalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRental",
			Handler:    _RentalService_CreateRental_Handler,
		},
		{
			MethodName: "EndRental",
			Handler:    _RentalService_EndRental_Handler,
		},
		{
			MethodName: "GetRental",
			Handler:    _RentalService_GetRental_Handler,
		},
		{
			MethodName: "ListRentals",
			Handler:    _RentalService_ListRentals_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/rental.proto",
}
