// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: rental.proto

package rental

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRentalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRentalRequest) Reset() {
	*x = GetRentalRequest{}
	mi := &file_rental_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRentalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRentalRequest) ProtoMessage() {}

func (x *GetRentalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rental_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRentalRequest.ProtoReflect.Descriptor instead.
func (*GetRentalRequest) Descriptor() ([]byte, []int) {
	return file_rental_proto_rawDescGZIP(), []int{0}
}

func (x *GetRentalRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRentalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	CarId         string                 `protobuf:"bytes,3,opt,name=carId,proto3" json:"carId,omitempty"`
	StartTime     string                 `protobuf:"bytes,4,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime       string                 `protobuf:"bytes,5,opt,name=endTime,proto3" json:"endTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRentalResponse) Reset() {
	*x = GetRentalResponse{}
	mi := &file_rental_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRentalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRentalResponse) ProtoMessage() {}

func (x *GetRentalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rental_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRentalResponse.ProtoReflect.Descriptor instead.
func (*GetRentalResponse) Descriptor() ([]byte, []int) {
	return file_rental_proto_rawDescGZIP(), []int{1}
}

func (x *GetRentalResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetRentalResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetRentalResponse) GetCarId() string {
	if x != nil {
		return x.CarId
	}
	return ""
}

func (x *GetRentalResponse) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *GetRentalResponse) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

var File_rental_proto protoreflect.FileDescriptor

const file_rental_proto_rawDesc = "" +
	"\n" +
	"\frental.proto\x12\x06rental\"\"\n" +
	"\x10GetRentalRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x89\x01\n" +
	"\x11GetRentalResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05carId\x18\x03 \x01(\tR\x05carId\x12\x1c\n" +
	"\tstartTime\x18\x04 \x01(\tR\tstartTime\x12\x18\n" +
	"\aendTime\x18\x05 \x01(\tR\aendTime2Q\n" +
	"\rRentalService\x12@\n" +
	"\tGetRental\x12\x18.rental.GetRentalRequest\x1a\x19.rental.GetRentalResponseB\x1dZ\x1brental-service/proto;rentalb\x06proto3"

var (
	file_rental_proto_rawDescOnce sync.Once
	file_rental_proto_rawDescData []byte
)

func file_rental_proto_rawDescGZIP() []byte {
	file_rental_proto_rawDescOnce.Do(func() {
		file_rental_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rental_proto_rawDesc), len(file_rental_proto_rawDesc)))
	})
	return file_rental_proto_rawDescData
}

var file_rental_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rental_proto_goTypes = []any{
	(*GetRentalRequest)(nil),  // 0: rental.GetRentalRequest
	(*GetRentalResponse)(nil), // 1: rental.GetRentalResponse
}
var file_rental_proto_depIdxs = []int32{
	0, // 0: rental.RentalService.GetRental:input_type -> rental.GetRentalRequest
	1, // 1: rental.RentalService.GetRental:output_type -> rental.GetRentalResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rental_proto_init() }
func file_rental_proto_init() {
	if File_rental_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rental_proto_rawDesc), len(file_rental_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rental_proto_goTypes,
		DependencyIndexes: file_rental_proto_depIdxs,
		MessageInfos:      file_rental_proto_msgTypes,
	}.Build()
	File_rental_proto = out.File
	file_rental_proto_goTypes = nil
	file_rental_proto_depIdxs = nil
}
